services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: wxread-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai  #
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 微信读书后端API服务
  backend:
    build:
      context: ./wxread
      dockerfile: Dockerfile
    container_name: wxread-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Shanghai
    ports:
      - "5000:5000"
    networks:
      - app-network

  # 前端Web服务
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: wxread-website
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - TZ=Asia/Shanghai
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: