networks:
    1panel-network:
        external: true
services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: wxread-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai  #
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - 1panel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 微信读书后端API服务
  backend:
    build:
      context: ./wxread
      dockerfile: Dockerfile
    container_name: wxread-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./wxread/.env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Shanghai
    ports:
      - "5000:5000"
    networks:
      - 1panel-network

  # 前端Web服务
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: wxread-website
    restart: always
    env_file:
      - .env
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    depends_on:
      - backend
    networks:
      - 1panel-network

volumes:
  mysql_data: